### ISSUE TITLE
Upgrade from 4.2.0.1 to 4.2.0.2 results in failure.

### ISSUE THREAD

**Issue by bdgregg** [tonesto7/echo-speaks#1004]
Upgrading via Hubitat Package Manager fails and results in role back when upgrading from 4.2.0.1 to 4.2.0.2.

Showing upgrade is available:
![image](https://user-images.githubusercontent.com/381166/163821948-a09d6902-8c50-438a-a814-6be05488e59b.png)

Showing role back:
![image](https://user-images.githubusercontent.com/381166/163822154-b9072454-d59d-40b7-b0c0-2502956b18db.png)

Showing Error Occurred During Insallation:
![image](https://user-images.githubusercontent.com/381166/163821787-0846b3f8-53c7-492d-9091-e13ee98300d3.png)

**Comment by Ja50n-Kru** [comment]
Issue is in Echo speaks - actions. Credit to thebearmay on forum. 

Since testMode is being passed and declared in the parameters as Boolean already it doesn't like the second declaration here in line 3938:

https://github.com/tonesto7/echo-speaks/blob/2c9d39cb905cf5244a8b8dc597934a40357e760d/apps/echo-speaks-actions.groovy#L3938

**Comment by Ja50n-Kru** [comment]
Fixed on republished version last night.

**Comment by bdgregg** [comment]
Confirming that the upgrade went through as expected now.  Thank you for the fix.

Screen shot from Hubitat Package Manager -> View Apps and Drivers:

![image](https://user-images.githubusercontent.com/381166/164010884-ceec6281-a748-47f5-bd61-57f568c3d5ef.png)
