### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by KenEsq** [tonesto7/echo-speaks#254]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [ x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): ST
-  How many devices are detected?: 15
-  iOS or Android?: Android
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**
Using door Chime smart app open door should be announced on various Echoes
## Current Behavior
**What happens instead of the expected behavior?**

This worked perfectly until last update. Now it only works one in ten times

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by JamesMarcum** [comment]
Answers inline below

    On Sunday, February 23, 2020, 4:15:10 PM PST, KenEsq <notifications@github.com> wrote:  
 
 
Verify the following before opening an trouble issue

Go over all the following points, and put an x in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!
   
   - [ x] That OAuth is Enabled for the SmartApp under the IDE.
   - [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
   - [ x] You have reviewed the Echo Speaks Documentation for potential fixes.
   - [ x] That Both the Apps/SmartApps and Device Handlers/Drivers have been Published for You in the IDE.

About Your Setup
   
   - Hub Platform (SmartThings or Hubitat): ST
   - How many devices are detected?: 4 installed, 3 unused/unsupported   

   - iOS or Android?: Android
   - Mobile App Version(Not required):
   - App/SmartApp Version:  3.5.0.0   

   - Device Handler/Driver Version:  3.5.0.0   

   - Heroku Server Version: 2.3.1   


Expected Behavior

tell us what should happen

Device testing/Speech test: Should speak   

Current Behavior

What happens instead of the expected behavior?
No speech.

Steps to Reproduce (for bugs)

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant
   
   - Select "Speech Test"   

   - Select any and/or all devices   

   - Set speak volume to 80 (or 90 or 100 or 5)   

   - Select "Perform the Speech Test"
   
   - Tried "Save" first as well, same thing - toggle button moves back to unselected on Perform speech test immediately   


Context

**How has this issue affected you? What are you trying to accomplish?Want to start using the app


Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by rfoust** [comment]
I had this same problem on Hubitat when I installed it the other day.  I'm new though so wasn't sure if I was doing something wrong or not.

Also I was setting up some rules to announce to two echo devices, and I see the following in the logs.  Not sure if it's related, maybe some kind of rate limit with Amazon?  I can do some more troubleshooting if needed.

```dev:122020-02-26 05:18:56.342 pm debugwasLastSpokenToDevice: false
dev:122020-02-26 05:17:50.703 pm info Echo (v3.5.0.0) | SpeakCommand Sent | (Indoor Blink cameras are now disarmed!) | Runtime: (4 sec) | QueueItems: (0) | Execution Time: (4458ms)
dev:122020-02-26 05:17:46.607 pm warn Echo (v3.5.0.0) | speechCmd | Too Many Requests Made to Amazon | Msg: Too Many Requests
dev:112020-02-26 05:17:45.439 pm info Echo (v3.5.0.0) | SpeakCommand Sent | (Indoor Blink cameras are now disarmed!) | Runtime: (4 sec) | QueueItems: (0) | Execution Time: (463ms)
app:52020-02-26 05:17:45.011 pm debugCreating Trigger Event(trigger_off) - Indoor Blink Cameras(switch: off)
dev:92020-02-26 05:17:44.850 pm infoIndoor Blink Cameras was turned off
app:62020-02-26 05:17:43.365 pm debugwebhookEvent ending
app:62020-02-26 05:17:43.312 pm debugcalled arrived
```

**Comment by tonesto7** [comment]
@rfoust Yeah Amazon has been implementing more and more rate-limits.

@JamesMarcum I've seen this happen when devices are new.  I have to speak to them once before they work.
