### ISSUE TITLE
Unable to add smartapp

### ISSUE THREAD

**Issue by jdpea** [tonesto7/echo-speaks#394]
I can get to step 4 of the app configuration documentation but once I click on the Echo Speaks app I get an error "Something went wrong"
"We can't load your screen right now"
![Screenshot_20201022-235400_SmartThings](https://user-images.githubusercontent.com/73321925/96955212-0df0df80-14c3-11eb-81b8-6caa927ee099.jpg)

**Comment by tonesto7** [comment]
Last I checked the classic mobile app is now disabled. Try using the new SmartThings app

**Comment by jdpea** [comment]
I tried it with both, same result.

**Comment by dcfurst** [comment]
I have the same problem in new Samsung app.  
![IMG_1849](https://user-images.githubusercontent.com/24395446/97816237-e25bbb00-1c61-11eb-8325-a6f5beac1fbe.jpeg)
![IMG_1850](https://user-images.githubusercontent.com/24395446/97816260-0d460f00-1c62-11eb-8459-351fb7eb6448.jpeg)

**Comment by madenwala** [comment]
I have the same issue!  On the new app, "Something went wrong. Please try to install the SmartApp again."

I've tried resetting the device and the first thing I did was install this SmartApp.  The only thing that might be weird is that the SmartApp was already available in the list of options. It's weird because I went through the reset button and the SmartThings hub and booted up after 30 seconds.  Any ideas would be welcome!

**Comment by madenwala** [comment]
@tonesto7 This is in the new app, FYI.

**Comment by madenwala** [comment]
@tonesto7 is Echo Speaks done on the new SmartThings platform? I'm reading that it might be toast :/

**Comment by hageson** [comment]
I have exactly the same issue.

**Comment by h00pz** [comment]
Same problem, seeing " java.lang.reflect.UndeclaredThrowableException @line 551 (logField)" in the live logs when attempting to add the app.
