### ISSUE TITLE
(BUG)019-07-10 01:47:41.988 pm errorjava.lang.NullPointerException: Cannot set property 'updatedDt' on null object on line 2082 (startPage) app:6172019-07-10 01:47:41.973 pm infoSuccessfully Retrieved Developer Notices from GitHub Repo... app:6172019-07-10 01:47:41.750 pm infoSuccessfully Retrieved (v2.0) of AppData Content from GitHub Repo... --- Loading Past Logs... ---

### ISSUE THREAD

**Issue by samgann** [tonesto7/echo-speaks#95]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat):
-  How many devices are detected?:
-  iOS or Android?:
-  Mobile App Version(Not required):
-  App/SmartApp Version:
-  Device Handler/Driver Version:
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by samgann** [comment]
Im getting the above error after installing App/Device on Hubitat.
Oath is enabled and saved. 
Then go to add user app and click on Echo Speak.
Window pops up with the above error.

**Comment by samgann** [comment]
Im getting the above error after installing App/Device on Hubitat.
Oath is enabled and saved.
Then go to add user app and click on Echo Speak.
Window pops up with the above error.

**Comment by samgann** [comment]
When I go to user apps and click on ECHO Speaks this what happens:
Latest Version of Dev and App still.
ava.lang.NullPointerException: Cannot set property 'updatedDt' on null object on line 2069 (startPage)
app:6562019-07-11 12:11:12.332 pm infoSuccessfully Retrieved Developer Notices from GitHub Repo...
app:6562019-07-11 12:11:12.038 pm infoSuccessfully Retrieved (v2.0) of AppData Content from GitHub Repo...
--- Loading Past Logs... ---

**Comment by zuhairmahd** [comment]
I am having the same issue using a SmartThings V2 hub.
1. Verified both DTH and App are published and are the latest version
2. Went through the documentation, uninstalled and reinstalled twice to verify.
Upon installing the app, whether using the ST Community Installer or installing from repo via GitHub integration, here is what happens:
1. Everything installs fine from repo and/or via ST Community Installer.
2. Under Smart App Setup (https://tonesto7.github.io/echo-speaks-docs/#/docs/installation/configuration/appConfig):

Step 1:
On your mobile device, open the SmartThings Classic App.
Tap on the Automation tab.
[Works as expected]

Step 2:
Scroll to the bottom of the screen and tap on + Add a SmartApp
[Works as expected]

Step 3:
Scroll to the bottom of the screen again and tap on + My Apps.
[Works as expected]

Step 4:
Scroll until you find Echo Speaks and tap on it to start the install process.
[Fails:
Expected behavior:
Should now be in the main screen of the Echo Speaks SmartApp.
Actual result:
Smartthings mobile app hangs, and the following is displayed in the SmartThings IDE live log:
993e8407-95d0-4980-a526-7673dd8ab745  6:26:39 PM: error java.lang.NullPointerException: Cannot set property 'updatedDt' on null object @line 2069 (getDaysSinceUpdated)
993e8407-95d0-4980-a526-7673dd8ab745  6:26:39 PM: info Successfully Retrieved Developer Notices from GitHub Repo...
993e8407-95d0-4980-a526-7673dd8ab745  6:26:39 PM: info Successfully Retrieved (v2.0) of AppData Content from GitHub Repo...]

Thanks.

**Comment by golanremi** [comment]
@tonesto7 I'm having the exact same issue. It happened when I tried Manual or github or community installer. Previous version worked with no issue.

**Comment by japhule** [comment]
@tonesto7 Having the same issue on Hubitat after installing smartapp and device driver.
java.lang.NullPointerException: Cannot set property 'updatedDt' on null object on line 2069 (startPage)

**Comment by jsdray** [comment]
Same problem with ST Hub v2.  Installation hangs after clicking Echo Speaks in iOS app.  Found this error in the IDE Live Logging.  
error java.lang.NullPointerException: Cannot set property 'updatedDt' on null object @line 2069 (getDaysSinceUpdated)

**Comment by golanremi** [comment]
Any update on this one?
